apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: toolbox-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: in-cluster
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: toolbox-app
    spec:
      project: default
      source:
        repoURL: https://github.com/brandtastic80/toolbox
        targetRevision: 0.1.0
        path: .
        directory:
          include: pod.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
